M48
; DRILL file {KiCad 7.0.8} date Sat Oct  7 15:53:13 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-07T15:53:13+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X28.575Y48.37
X33.425Y48.37
T2
X28.275Y51.4
X33.725Y51.4
T3
X4.0Y50.0
X4.0Y4.0
X50.0Y50.0
X50.0Y4.0
T0
M30
